CREATE TABLE Orders (
	OrderID INT PRIMARY KEY IDENTITY(1,1),
	CustomerID INT NOT NULL,
	OrderDate DATETIME DEFAULT GETDATE(),
	CONSTRAINT FK_Orders_Customers 
		FOREIGN KEY (CustomerID) 
		REFERENCES Customers(CustomerID) 
		ON DELETE CASCADE
	);