-- MySQL Script generated by MySQL Workbench
-- Thu Apr  3 15:21:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fssdemodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fssdemodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fssdemodb` DEFAULT CHARACTER SET utf8 ;
USE `fssdemodb` ;

-- -----------------------------------------------------
-- Table `fssdemodb`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fssdemodb`.`Customers` (
  `CustomerID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CustomerID`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fssdemodb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fssdemodb`.`Orders` (
  `OrderID` INT NOT NULL AUTO_INCREMENT,
  `CustomerID` INT NULL,
  `OrderDate` DATE NOT NULL,
  `Amount` DECIMAL NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `FK_Customers_idx` (`CustomerID` ASC) VISIBLE,
  CONSTRAINT `FK_Customers`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `fssdemodb`.`Customers` (`CustomerID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
